### ISSUE TITLE
Unable to load multiple protocols on tablet

### ISSUE THREAD

**Issue by lleleux** [codaco/Network-Canvas#1001]
Hi,

On a tablet (Huawei MediaPad M5, android 8.0), I'm unable to load multiple protocols. It works on a computer (Linux, Windows) but not on Android.

I start Network Canvas -> load protocol from file -> it appears on the start screen.
When I load a second protocol, also from file, it is visible on the start screen, but the first one is no more visible. When I try to scroll left/right there is nothing, and the left/right arrows are not working (disabled).

If you need more information about this, feel free to ask.

Thank you very much for your work !

Laurent Leleux

**Comment by jthrilly** [comment]
Hi Laurent - thanks so much for this report. We will look into this for you.

If possible, could you please email the two protocols you are using to info@networkcanvas.com?

**Comment by lleleux** [comment]
I sent them by mail just now.

Just for information, I tried with new fresh empty protocols, and the issue not appeared. I was able to add them with keeping access to the two protocols.
When adding the buggy protocol 1 to the two new protocols, I see now the three protocols. And when adding the buggy protocol 2, the protocol 1 was replaced by the 2. So I see only three protocols instead of 4.

Thank you,

**Comment by jthrilly** [comment]
Thanks for the additional info - hopefully this will be a simple logic error, based on what you have said.

**Comment by wwqrd** [comment]
I believe this might be a naming issue (or related to how protocol names are generated). When two protocols have the same file name they are considered to be the same protocol, and the previous one is replaced. Might be something broken in how that name is detected in Android, or that they are being given the same file name temporarily.

@lleleux Would you mind trying something to confirm that's what's going on in your case?:
1. import the first of the conflicting protocols
2. create a session using that protocol
3. try to import the second of the conflicting protocols, you should get a warning that "This protocol is already installed."?

I'd like to suggest an additional improvement whether or not this turns out to be the case -- we should always warn the user (and give them the option to cancel), when another protocol will be overwritten!

**Comment by jthrilly** [comment]
> I'd like to suggest an additional improvement whether or not this turns out to be the case -- we should always warn the user (and give them the option to cancel), when another protocol will be overwritten!

We did consider this at the time, but since importing is such a deliberate action, and since (if the logic is correct) no data should be lost, it seemed redundant. You might be right that it is better to notify though!

If we do it, let's make sure its not a scary notification (an information type dialog should suffice).

**Comment by jthrilly** [comment]
Fixed in #1038
