### ISSUE TITLE
"Variable registry" - a component that contains a list of variables, how they are defined, validation functions, etc. Provides an api for other modules/interfaces and the interview protocol to register variables

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#130]

**Comment by jthrilly** [comment]
I'm reopening this with more details to follow. 

Basically I think it would be advantageous to have some kind of registry for variables used in the interview. Other components/views could reference this registry to enhance their functionality, or simply to better understand the nature of a variable.

Examples:

- Coordinates can be stored on any variable, but the exporter functionality needs to know which variables are intended to store these values because some file formats require special syntax for these variables. 
- Variable constraints could be defined in the registry and attached to variables, meaning that we don't need to duplicate validation code. This could be redux-form compatible. 
- The registry could also contain human readable descriptions of variables, which could be used by Architect and Server.

More to come.

**Comment by wwqrd** [comment]
Had a little think about this.

We have three points of variable creation at the moment:

- `nodeAttributes`
- layouts
- form fields

I think it probably does make sense to have a collated variable registry for these, which would include data types and other meta data. Perhaps we can leverage `PropTypes` for the data types.

Where these variables are defined currently would be replaced with a reference to the variable. Perhaps by name, or perhaps a literal reference.

For one it'd mean we can simplify the export methods.

I'm not convinced it makes sense to put validation data in the registry: what do we do with data that doesn't match the validation requirements? When would data be validated? I think these questions don't make sense because the validation is specific to the forms.
