### ISSUE TITLE
Enforce some stricter linting (JS/SASS)

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#162]
For javascript we're already using eslint, but without many rules, perhaps we could start from the airbnb ones, and also add the react rules: https://github.com/airbnb/javascript/tree/master/react

For sass we could use sass-lint. I'm not sure what rules we want from this except to enforce hyphenatedbem

**Comment by jthrilly** [comment]
Great suggestion, and happy to go ahead with it. I've heard that Airbnb is extremely prescriptive, and somewhat controversial for some of its decisions. We might want to soften it back from that. 

I'm not sure how to handle this since there's probably some existing code that will break, but you could do it as a fix branch against master that people can pull in to any active PRs and manage themselves, maybe? Or we could just put it straight into master and deal with the pain when we open PRs.

**Comment by jthrilly** [comment]
I see @wwqrd went ahead and did a PR and mentioned the Airbnb linting. Steve: if you think that's the best way to deal, let's go for it.

**Comment by wwqrd** [comment]
Pain is the right word for it, this breaks everything!
