### ISSUE TITLE
Providing whole networks for edge generation and annotation

### ISSUE THREAD

**Issue by lizmcconnell** [codaco/Network-Canvas#184]
From focus group on July 7, 2017: This suggestion came out of a conversation on bullying research - can imagine a scenario where it might be useful to provide a classroom of students with a screen including all of the alters in the classroom. They could then arrange them into groups and generate edges, and report on perceived behaviors (e.g., bullying perpetrators and victims). @michellebee

**Comment by jthrilly** [comment]
I'm hoping that this functionality is possible with the features we already have planned (#127 #264 #265). This sounds like it is really just a roster-type interview, where instead of nominating alters all alters are known at the start of the interview, and are 'pre-loaded'. This way the participant can start right away on the sociogram screen. Please update me if I'm mistaken.
