### ISSUE TITLE
Use animation to improve discoverability of primary interface interaction

### ISSUE THREAD

**Issue by katebanner** [codaco/Network-Canvas#199]
From demo feedback meeting with Cui Yang on 7/28/2017: 
Cui suggested that we add animations (e.g. glowing/bouncing/etc.) to the sociogram screen so that participants know that nodes should be pulled down from the top. Animations would "highlight" walk through of the app.

We may also want to consider adding animations to other screens on the app (and maybe the architect as well) that will improve flow and minimize the need for explanation or direction from the researcher during the interview.

**Comment by jthrilly** [comment]
# Purpose
Improve the discoverability of the primary interactions of each interface, using animation

# Specification
- Add a glowing/bouncing effect to the following elements, _only when they are first shown_:
  - The add new node button
  - The sociogram node positioning bucket

This effect should be cancelled once the component has been used once. It probably makes sense to store this in the session properties.

**Comment by rebeccamadsen** [comment]
> This effect should be cancelled once the component has been used once

By "used", do we mean clicked on? Hovered? Completed the entire new node form? I think clicked on once is probably the right level, but there are other possibilities.

Also, the new node button is a button with an svg, which has overlapping circles. I assume a "glow" would outline image like nodes can glow, but that we would want to outline the outside of both circles and not their intersection? Is that right? Or is there a different look and feel we're going for here?

**Comment by jthrilly** [comment]
> By "used", do we mean clicked on? Hovered? Completed the entire new node form? I think clicked on once is probably the right level, but there are other possibilities.

This is a tricky one. Ideally, it would be on a 'per interview' level, meaning once a button or component has been used in an interview on a specific screen, it no longer highlights _within that interview on subsequent screens_. However, that would require some sort of temporary 'session settings' data object. We can discuss this more when we implement.

> Also, the new node button is a button with an svg, which has overlapping circles. I assume a "glow" would outline image like nodes can glow, but that we would want to outline the outside of both circles and not their intersection? Is that right? Or is there a different look and feel we're going for here?

The way that button is implemented currently is not consistent with other button or icon components. I believe it actually references an SVG file directly from within the NC source tree, rather than using a UI component. In this case, the functionality should be built into the UI component, as a prop. @wwqrd?

Aside from that, we don't actually have a UI pattern for what the glowing effect should be. Happy for the implementor to be creative :)
