### ISSUE TITLE
Panel animation performance is terrible

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#211]
Animating the panels has awful performance, and causes stuttering on elements that otherwise animate smoothly when panels aren't also moving.

We have previously discussed the need to animate certain non-optimizable properties (primarily `left` and `width` if I recall), but I really think we need to think again about how to implement this.

The following article has an approach that I think could work: https://developers.google.com/web/updates/2017/03/performant-expand-and-collapse#top_of_page

**Comment by wwqrd** [comment]
We're currently animating flex: https://codepen.io/steeeve/pen/eEVgRL/, which I think is inherently un optimisable due to to the fact this changes the page layout (in fact we do this *in order to* update the layout).

Scale doesn't affect the layout: https://codepen.io/steeeve/pen/brLgmY so we'd have to look at another way of achieving the same draw shrinking effect, perhaps absolute positioning the panels + padding on the node list container - but that might just be moving the layout redrawing issue.

**Comment by jthrilly** [comment]
I think absolute positioning (using `vw` for padding?) could be the winner. Let's just leave this open for now, but pushed back until later when we can think about it more broadly.

**Comment by wwqrd** [comment]
One possible approach would be to use grids for the layout: https://codepen.io/steeeve/pen/dzLRMg

**Comment by jamieshark** [comment]
@wwqrd - The grid demo jumps a bit for me on mouseout. Is that expected?

**Comment by wwqrd** [comment]
@jamieshark It's a sort of compromise. We need to reflow the main window, but transitioning it hammers the cpu. In this case the panel can be transformed using the gpu down to nothing, and the main area is instantly updated to fill the space behind it (limiting redraws). Not sure how this approach would work for multiple left hand columns though.

**Comment by jthrilly** [comment]
@wwqrd did this get implemented, or were we still discussing?

**Comment by wwqrd** [comment]
Not as far as I know, but it's not assigned to me?

**Comment by jthrilly** [comment]
Okay, let's put this to one side and return to it again if we see an issue.
