### ISSUE TITLE
NameGeneratorList doesn't update nodes when `showExistingNodes` is enabled

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#304]
It seems that "showExistingNodes" allows nodes to remain visible between prompts — i.e., be used as an answer to more than one question.

Assume an Interviewer's protocol includes a Roster list with "showExistingNodes=true"; the interface has two prompts: p1 asks "who do you talk to?" and p2 asks "who are you close to?". Both draw from schoolPupils, an externalData set containing "Eu", who has a pre-defined uid. In the GUI, User adds "Eu" to prompt 1, and moves to prompt 2. User sees "Eu" selected in prompt2, even though "Eu" represents a node that has been "talked to", and not "close to".

Setup Steps:
1. Edit "showExistingNodes" the protocol.json so that `"showExistingNodes": true`.

GUI Steps:
0. Load demo protocol
1. Go to Roster List
2. Select "Eu"
3. Go to next prompt
4. Search for "Eu"

Observed:
- "Eu" is selected, though I've only selected Eu as an answer to prompt 1.
- If I remove & re-add, then the `talk_friend` attribute from prompt 1 is lost.

Expected:
(I think) I should be able to toggle "Eu" on the second prompt to toggle the `close_friend` attribute without affecting `talk_friend`.

**Comment by rebeccamadsen** [comment]
So this is something I feel we haven't come to a complete solution on. It is by design to be able to toggle whether to show the existing nodes. Either mode (show/hide existing nodes) has different effects. As I mentioned [here](https://github.com/codaco/Network-Canvas/pull/293#issuecomment-360851048) (second paragraph), I am not sure the implications of how to add/remove prompt attributes in this particular mode. I settled on just adding the prompt attributes for the prompt the node was added on, but we could also add prompt attributes for all the remaining prompts in the stage. I think either could make sense depending on the use case. Unfortunately the use case isn't really fleshed out, so I left this as an open question.

Assuming the roster list is used to add nodes to the network, and that is all we care about, this feature allows users to see that they have already added a certain node (in case they might be confused about why a certain node is unavailable to them), and each subsequent prompt allows them to continue building their network. But the flip side is that removing a node on a subsequent prompt removes that node from the network entirely.

I left the other mode, to hide existing nodes, as the default behavior because I think it is more obvious how to address prompt attributes when users just aren't allowed to choose from already added nodes.
