### ISSUE TITLE
Documentation pages for Alpha 2 interfaces

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#323]
We need documentation in the wiki to describe the APIs for the three new interfaces created for this release (information interface, roster list, and roster autocomplete). 

- [x] information interface
- [x] roster list
- [x] roster autocomplete

**Comment by bryfox** [comment]
I added an initial version of [autocomplete](https://github.com/codaco/Network-Canvas/wiki/Name-Generator%3A-Roster-Search-with-Autocomplete).

Since some of the protocol is shared with the roster list; we could just copy that information for now, and (pending completion of #300) eventually extract the shared interface & examples.

**Comment by wwqrd** [comment]
Added instructions interface here: https://github.com/codaco/Network-Canvas/wiki/Information-Interface

**Comment by rebeccamadsen** [comment]
And there is [this](https://github.com/codaco/Network-Canvas/wiki/Name-Generator:-Roster-List) now.
