### ISSUE TITLE
Make factory protocols loadable via router

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#326]
In order to speed up development work and make better use of hot-reloading we would like to be able to load a specific factory protocol using URLs in development, for example:

`http://localhost:3000/#/protocol/<protocol-name>`

Additionally we would like to be able to load a specific stage number:

`http://localhost:3000/#/protocol/<protocol-name>/<stage-number>`

**Comment by rebeccamadsen** [comment]
Is this something we want to allow in development only, or to just allow in general with development in mind?

**Comment by wwqrd** [comment]
I think the second. Does anyone know why it might be bad to allow this generally considering the URL bar won't be visible and we are assuming the user has permission to access the protocols anyway?

**Comment by jthrilly** [comment]
There aren't any security issues with this that I can think of, and I agree that we want this to be general case - not just for development.

**Comment by rebeccamadsen** [comment]
We keep the stage number in redux. If we allow a stage number in the URL to change the current stage, would we want to update the next/previous buttons and the menu to use links instead? Otherwise there is a potential disconnect between the URL and the stage, right?

**Comment by jthrilly** [comment]
We want to synchronize them, yes.

The desired result would be the following:
`/protocol/<protocol>/` with no in-progress interview redirects to `/protocol/<protocol>/0` 

`/protocol/<protocol>/` with an in-progress interview (found in redux) redirects to `/protocol/<protocol>/14`. 

Ultimately, and I am kind of dreading this, we will need to change our store structure to support multiple in-progress interviews. If that shapes your design decisions now, great, but otherwise don't worry about it.

We don't have to do that now, unless its easy to implement along with this.

**Comment by rebeccamadsen** [comment]
Loading from the url is different than loading an in-progress interview. I think you might *have* to support multiple in progress interviews in order to allow loading an in-progress interview, or you have to have fancier intermediary error handling because it's possible a stage number from the last open protocol (found in redux) is not valid for the url's specified protocol.

**Comment by jthrilly** [comment]
Sorry, reading that back I can see how unclear my comment was.

What I was trying to describe was the relationship between the data in our redux store, and the intended route described in the URL. In other words, which of these has authority over the other, and under what circumstances?

Basically, if the URL doesn't provide an 'opinion' (i.e specify) a stage to navigate to, the current stage in the redux store should be used, and If the URL _does_ specify a stage, we obviously navigate to it (and handle logical errors there, such as a stage not existing). This is the part I think you already understand, and are working on.

The complication (which I did a bad job of introducing) relates to planned functionality: supporting multiple in-progress interviews for a given protocol. This will require modifying the data structure of our redux store, and probably introducing something like a session ID to index these by. I thought this might be relevant to design of this feature, but now I reflect on it, it is obviously out of scope.

Hope that is clearer.
