### ISSUE TITLE
Ignored attempt to cancel a touchmove

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#331]
I saw this on the remote console while running Android in debug mode on a simulator, but there don't seem to be any ill effects that I can see, so this may be something we could ignore. Especially if it doesn't show up on device, but I can't test that myself.

While dragging nodes around, this error crops up multiple times, over and over as long as you keep dragging:
```
main.d96239b5.js:218262 Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
detectMoveType	@	main.d96239b5.js:218262
onMove	@	main.d96239b5.js:218304
```

It does not show up in Electron or Chrome.

**Comment by bryfox** [comment]
I looked at this a bit; code seems correct in use of `passive`. 

Further, if I comment out the line it claims to be ignoring, then the drag doesn't work properly; I can 'pick up' a node and then have my touch scroll the container instead of tracking drag.

I'm not sure there's anything we should do here other than leave a related comment in the code, but @wwqrd knows more about drag/drop...

**Comment by jthrilly** [comment]
I'm going to close this because it doesn't seem to be an actual bug.
