### ISSUE TITLE
Scroll vs Drag detection is creating a poor user experience

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#342]
## Overview

We have struggled to reconcile two behaviors in our node lists: the ability to drag nodes out of the list, and the ability to scroll the list.

When using a mouse, there is no ambiguity about the intended outcome. With touch, we have to try and differentiate between the user attempting to scroll a node list, and attempting to drag a node out of it. 

The current algorithm is relatively close, but will always be a tradeoff between false scroll detection and false node dragging. Currently, you must drag nodes very slowly to trigger the drag start. This can be very frustrating and confusing. At the same time, scrolling does not work well on touch devices, since all seem to behave differently. 

To test: Either use a touch screen device, or use the device emulation functionality in Chrome debug tools. Notice that dragging too quickly prevents the node from dragging at all. Notice that scrolling a container (particularly the Name generator side panels) can be very difficult, and is not fluid.

## Short term fix

In the short term, we need to change the sensitivity to velocity in `behaviour/DragAndDrop/DragManager` so that faster movements are considered part of a drag, rather than a scroll. Alternatively we could tighten up the part that pertains to the angle to be less sensitive to more sideways movement.

## Long term

In general I think this situation needs improving. Scrolling works find on Android, but is a pain still on iOS. Dragging can sometimes feel broken, especially since the natural response to a failed drag is to go back and drag and node again even more furiously, thereby making the check fail again.

I had this working in the prototype using jQuery UI and a standard scrollable DIV without any trouble whatsoever. Perhaps we can look back to that for some inspiration. 

In the meantime, I would appreciate any reviews of the existing implementation, and experimentation/speculation about how we can improve this.

On the speculation front, one option is a different UI pattern. We reveal an affordance for scrolling the container, like a scrollbar/pad, and only listen for scroll events on that area.

**Comment by wwqrd** [comment]
https://github.com/jquery/jquery-ui/blob/89af4c292eaa5fc1c83437ca71085264dcbef34a/ui/widgets/draggable.js#L1020 (edited)

I haven’t looked in great depth, but I get the impression that this library captures scrolling too? Whereas `DragManager` defers to the device. Changing this might make it easier to improve the behaviour.

**Comment by wwqrd** [comment]
Might relate with: #331

**Comment by bryfox** [comment]
As a user (iOS/Android), I would expect to *long press* to initiate a drag inside a scrolling area. Velocity of the actual dragging shouldn't matter. The current calculation must take that initial pause into account, because the UI mostly works as expected for me. Though I would expect a slow drag (without long press) to scroll, not drag. Material has a little bit to say about [drag vs long-press drag](https://material.io/guidelines/patterns/gestures.html#gestures-touch-mechanics).

I think the notable difference with that is that drag mode is recognized before touchmove. So the targets appear and the user knows the touch-to-drag succeeded by just doing the hold. No need to accidentally scroll.

A couple of other things that might help, in addition:

- In addition to styling 'droppable' state, the drag target should change in some way once drag mode is recognized (size, opacity...).
- On iOS, in addition to above, the recognition of a touch is typically confirmed by highlighting the touched item briefly... this communicates that first recognition immediately ...which can prevent frustration in those cases when the touch doesn't register...
- I assume there was a good reason not to use native scrolling, but if that's a possibility, it might make things feel more familiar? Right now there seems to be a lot of friction, so I end up using many more touches to scroll than expected, and that sometimes triggers a false drag.

**Comment by jthrilly** [comment]
> As a user (iOS/Android), I would expect to long press to initiate a drag inside a scrolling area. Velocity of the actual dragging shouldn't matter. The current calculation must take that initial pause into account, because the UI mostly works as expected for me. Though I would expect a slow drag (without long press) to scroll, not drag. Material has a little bit to say about drag vs long-press drag.

I think the issue here is that we have reserved the long press interaction for other (as yet unimplemented) things. Namely, we want to be able to long press a node a trigger a kind of "global property" editor, so that the interviewer can fix data issues within the interview. 

The other aspect to this is that dragging elsewhere in the interview is just short touch. And necessarily so - it is one of the primary actions within the app. For this reason, adding a delay to drag from side panels is also undesirable. 



> I assume there was a good reason not to use native scrolling, but if that's a possibility, it might make things feel more familiar? Right now there seems to be a lot of friction, so I end up using many more touches to scroll than expected, and that sometimes triggers a false drag.

This is definitely worth investigating. I've noticed that the actual scroll doesn't feel good, too.

**Comment by bryfox** [comment]
If it's important to have dragging without a long press, I won't say too much more, except:

- If it's "easy" to *also* support support long-press dragging (i.e., to determine drag state on a long press so that target states/styling are updated), that would be nice. (My intuition, until I read this issue, would be to repeat a failed node drag by holding longer, not dragging at a different speed.)
- Using long press to trigger a drag doesn't preclude other functionality tied to it (UX-wise). Examples from home screens: an android app icon (e.g., Slack's) becomes draggable at the same time context menus are shown; longer-pressing on iOS icons triggers a mode for app deletion.

**Comment by wwqrd** [comment]
> Though I would expect a slow drag (without long press) to scroll, not drag

I think this would be worth a try.

**Comment by wwqrd** [comment]
> Using long press to trigger a drag doesn't preclude other functionality tied to it (UX-wise). Examples from home screens: an android app icon (e.g., Slack's) becomes draggable at the same time context menus are shown; longer-pressing on iOS icons triggers a mode for app deletion.

So we could do:
- Long-press and don't move -> show menu
- Long-press and move -> drag
- Move after menu is shown -> hide menu

**Comment by jthrilly** [comment]
I think long press to drag is out of the question - it will just be too tedious to drag from the side panels on to the main node list in the name generator. This is something that a participant may want to do 10 times in quick succession. 

> Though I would expect a slow drag (without long press) to scroll, not drag
> 
> I think this would be worth a try.

Yes, this would make more sense, and might even be the missing piece of this.

**Comment by rebeccamadsen** [comment]
Would it make sense to allow both long-press+move and short-press+move to drag nodes? Or does that go back to the statement about reserving that long-press for other things? Having both trigger a drag would allow the user to do a quick succession if the app is responding quickly, but would be a nice fallback for when the app is slow to respond. I think it is natural for users to over-emphasis presses and movement when they are frustrated, and in this case that would make the interaction worse. Of course watching users interact with the app would give the best answer to that.

I like Bryan's idea to give visual feedback of some kind when the user touch is registered. It could make them slightly less frustrated if they know when the app is starting to do something.

**Comment by jthrilly** [comment]
> Would it make sense to allow both long-press+move and short-press+move to drag nodes?

The thing is, this doesn't resolve the underlying issue. The app should always be responsive to our fundamental interactions. The fact this was implemented and working correctly in a very simplistic jQuery UI based prototype means it is possible. 


> I like Bryan's idea to give visual feedback of some kind when the user touch is registered. It could make them slightly less frustrated if they know when the app is starting to do something.

There _is_ visual feedback - if the app detects a scroll, the container scrolls (visual feedback). Likewise with a drag. The only additional feedback I can think of doing would be some sort of self-decaying 'focus', but again I don't think this is getting to the root of the issue.

**Comment by jthrilly** [comment]
Here is a proof of concept I put together with jQuery UI showing that good scrolling and good drag responsiveness are not mutually exclusive: https://codepen.io/jthrilly/pen/yvozKJ

Can anyone shed any light on why this works, but our approach doesn't?

**Comment by jthrilly** [comment]
It might be @rebeccamadsen - but when would we drag when not touching a node? When would we scroll when not touching the container? Is that how our current system is built? If it is, that may be the fundamental issue. We do not need to second guess the user by attempting to allow scrolling 

If this _is_ a simplification, it is one we need to adopt. 

**Okay, I've done more testing this morning and here is what I would like us to try:** 
- Use native scrolling. The lack of momentum based scrolling, coupled with the complexity of calculating scroll vs drag are the biggest issues here. Let's just let the browser handle scrolling with touch natively.
- Make sure our drag handlers are bound to the node SVG itself, and not to the component (which has padding/margin.


Given the scope of this change, I have bumped it to the next release.
