### ISSUE TITLE
discrepancies in wiki vs implementation

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#359]
I noticed a few discrepancies, which could either be that the API is out of date or that we haven't implemented something correctly yet. Most:

- there is an option for a `newNodeForm` [specified](https://github.com/codaco/Network-Canvas/wiki/Name-Generator) for the `NameGenerator` interface, but not yet implemented as far as I can tell.
- the `NameGenerator` says `panels` defaults to `['existing']`, but it defaults to nothing if you leave `panels` off the protocol
- `icon` is optional in [here](https://github.com/codaco/Network-Canvas/wiki/General-Interface-API), but doesn't actually update the icon used in the menu for a stage
- `content` is specified as optional for information interface, but `items` is actually required (at least an empty array)
- `sortOptions` is [optional ](https://github.com/codaco/Network-Canvas/wiki/Name-Generator:-Roster-List)for NameGeneratorList, but errors out if you leave it off (needs an empty object).
- `searchOptions` is optional for [NameGeneratorAutoComplete](https://github.com/codaco/Network-Canvas/wiki/Name-Generator:-Roster-Search-with-Autocomplete), but errors if you leave it off (needs an empty object)

**Comment by jthrilly** [comment]
Good catches!

> there is an option for a newNodeForm specified for the NameGenerator interface, but not yet implemented as far as I can tell.

This was changed to be just `form`, which is also present and defined. `newNodeForm` should be removed.



> the NameGenerator says panels defaults to ['existing'], but it defaults to nothing if you leave panels off the protocol

The implementation is correct here, so we need to update the doc.


> icon is optional in here, but doesn't actually update the icon used in the menu for a stage
Yep! Can you create an issue to implement this, please?



> content is specified as optional for information interface, but items is actually required (at least an empty array)
> sortOptions is optional for NameGeneratorList, but errors out if you leave it off (needs an empty object).
> searchOptions is optional for NameGeneratorAutoComplete, but errors if you leave it off (needs an empty object)

These three are grouped because they are an instance of a problem I've seen elsewhere with nested properties. Is there anything smart we can do better more systematically here? In the meantime, we should file an issue. I think one for all three, because it is the same issue and will have the same (or similar) fix.

**Comment by rebeccamadsen** [comment]
I updated the docs to remove `newNodeForm` and revise the default for `panels`, and created separate issues for the other items, so I will close this issue.
