### ISSUE TITLE
New Start Screen

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#388]
More info incoming. 

![screen shot 2018-02-16 at 1 37 22 pm](https://user-images.githubusercontent.com/1387940/36309998-8e730bd2-131e-11e8-9dc2-455e8ccb2559.png)

![screen shot 2018-02-16 at 1 37 51 pm](https://user-images.githubusercontent.com/1387940/36310019-a065e0e4-131e-11e8-9ee4-f009c88eedd1.png)

**Comment by rebeccamadsen** [comment]
Does this cycle between sessions, or between protocols? e.g. With more than one in-progress "Demo protocol", would that be multiple big rectangles to cycle through, or would there be buttons or dropdown with the in-progress interviews for each protocol? Are we expecting many in-progress interviews or many different protocols, or just many protocols or just many in-progress of a few protocols?

Are the triangles/arrows and the circle pips both the same action -- to cycle between "sessions"? Or is one cycling protocols and one cycling sessions?

If there are no in-progress interviews, are we showing information about possible protocols? If so, how are possible protocols to be populated, from a directory or from the Server, or something else?

Are the words "Start new interview" and "Resume interview" buttons/links, or is the "+" button in the bottom corner how a user commits to their selection? Or is that the button to pair with the server?

Are the blurbs/names/version about each protocol coming from the protocol itself? Does a protocol need to be loaded to get this information, or is it stored elsewhere?

Is this where we ask the question about whether the user wants to "forget" an in-progress interview? Is this a menu option, or a button, or a dragging to the trash kind of interaction?

Only the "sessions" menu looks visible in the top left; is the "stages" menu hidden at this point since their is no active protocol? Is there a menu option to return to the start screen, or should there be? If so, would that "unload" a protocol?

**Comment by jthrilly** [comment]
I've sent you a video on Slack, but just for completeness I'll also answer these questions here.

> Does this cycle between sessions, or between protocols? 

The screen you are seeing above is inviting the user to start a new interview session with a given protocol. So this is cycling through protocols.

The "Start new interview" text at the top is supposed to be a tab, with the other being "Resume Interview".

> Are we expecting many in-progress interviews or many different protocols, or just many protocols or just many in-progress of a few protocols?

There could be any number of installed protocols on devices, but likely not more than 4 or 5. Most commonly only one or two.

Each device will however likely have multiple interview sessions, which could be spread across these protocols. 



> Are the triangles/arrows and the circle pips both the same action -- to cycle between "sessions"? Or is one cycling protocols and one cycling sessions?

The pips are to show the progress through the slider, as with the prompts on the name generator, for example. The arrows allow cycling through if swiping is not preferred. I am personally a big fan of this swiper component: https://github.com/nolimits4web/swiper

Steve didn't want to use it for the prompts, but I think it makes more sense here as it is much more tactile.

> If there are no in-progress interviews, are we showing information about possible protocols? If so, how are possible protocols to be populated, from a directory or from the Server, or something else?

The protocol list here shows the currently installed protocols on the device. I don't know as we currently have a way to determine which protocols are installed. @wwqrd - do you have any thoughts?

If there are no in-progress interviews (let's just call them "interview sessions"), we will just say "No existing interviews." and provide a link to return to the other tab. We can flesh this out together.

> Are the words "Start new interview" and "Resume interview" buttons/links, or is the "+" button in the bottom corner how a user commits to their selection? Or is that the button to pair with the server?

The button triggers the flow for installing a new protocol to the device, which may or may not involve pairing with a server (Bryan has already implemented this in his server pairing branch). The words you mentioned are the tabs for the two main views.

> Are the blurbs/names/version about each protocol coming from the protocol itself? Does a protocol need to be loaded to get this information, or is it stored elsewhere?

Perhaps this relates to the question about how we know which protocols are available on the device - we might need to extend or implement the current method for installing a protocol to also create and populate a meta data object about the available protocols. This can live in redux, and could perhaps be the beginning of #390. If this happens, when the protocol is installed to the device, this meta data will be stored there, and this list will simply parse and display that object.

> Is this where we ask the question about whether the user wants to "forget" an in-progress interview? Is this a menu option, or a button, or a dragging to the trash kind of interaction?

I had imagined that we would have a similar "drag to trash" action to delete these in progress interviews, but this might not work depending on how we design that view. We could either have another swiper component, or more of a "card list" like you implemented for the roster interface. I think the latter would make more sense, as it would allow filtering and sorting, as well as the drag to the trash interaction. 


> Only the "sessions" menu looks visible in the top left; is the "stages" menu hidden at this point since their is no active protocol? Is there a menu option to return to the start screen, or should there be? If so, would that "unload" a protocol?

Session menu is visible, although from this point forward this will become the "app" or "settings" menu. Once in an interview session, this menu will contain a "Return to start screen" option, which will prompt the user to either keep or discard the in-progress interview. We shouldn't need to unload a protocol, because any subsequent navigation from this new start screen will automatically load the relevant protocol for what is being displayed.

The stages menu will be replaced by the timeline (#245).

**Comment by rebeccamadsen** [comment]
Closed via #526.
