### ISSUE TITLE
Sticky Baz

### ISSUE THREAD

**Issue by Defelt** [codaco/Network-Canvas#397]
when i reached the end of the list of classmates and dragged "Baz" over, rather than disappearing from the column on the left, the name stayed and I ended up dragging it in multiple times - because I had to scroll down in the right half of the screen to see names being added at the bottom, I'd already added it several times before I realized there was a problem. After that I just did it a few more times to see if it would resolve itself but it didn't seem to

![image 3](https://user-images.githubusercontent.com/36740723/36553260-7b19da6e-17c1-11e8-8fa5-5b44a7501fa2.png)

![image 3](https://user-images.githubusercontent.com/36740723/36553245-71dd186c-17c1-11e8-9530-2a82fd2de1b0.png)

**Comment by rebeccamadsen** [comment]
This reminds me of an issue I saw [here](https://github.com/codaco/Network-Canvas/pull/293#issuecomment-360851048). Basically, it is a bug related to Baz not having a uid in the dataset. The "quick fix" is to make sure Baz has a uid in the dataset, but the bug is because the uid is not generated until you drag it to the main list. And since the generated uid doesn't match the Baz node, Baz stays in the side panel as well. Dragging it again just creates a new uid over and over.

Interestingly, I also notice the "Annie" is in the dataset but not appearing in the side panel. Maybe that is related?

**Comment by wwqrd** [comment]
Perhaps we should make the following changes @rebeccamadsen @bryfox?:

1. External data *must* be provided with a `uid` (instead of an `id`).
1. Randomly generate `uids` for new nodes using something like this [uuid](https://www.npmjs.com/package/uuid), that way we can assume they won't clash with the user provided ones.
1. Remove the `id` property from nodes

**Comment by rebeccamadsen** [comment]
I think this greatly simplifies other issues we've seen in trying to solve uniqueness!

My only concern is from the user facing side. Is it acceptable from the user perspective to require `uid`s to be unique? I think within one dataset, sure. So how often will they use multiple data sets in the same interview? Does/will the Architect massage user data, or is that all on the user?

I suppose the interviewers have to be prepared to work with data at the end, when they export it, so it could be fair enough to expect them to present clean data at the beginning as well. I just want to make sure we've thought through the side effects of making `uid`s a user issue.

**Comment by wwqrd** [comment]
That's an interesting point, in fact they may *require* clashing ids. The user need for this feature is: "I have an ID from another study I want to use", and that could clash with other external data ids they want to use. That rings a bell when I think about why I implemented it like this.

Given that external data could come from an arbitrary source like csv, would make it difficult to enforce too.

**Comment by bryfox** [comment]
For newly-generated nodes, I think UUID makes a lot of sense.

Requiring users to provide UIDs would solve the related problems I've seen in various interfaces. (We could provide some flexiblity by allowing the protocol to define what "UID" means for an external data type — i.e. to support different keys or compound IDs.) But I'll assume for now this is not an option and float another idea.

If external data doesn't include a UID, I think my expectation would be that uniqueness be content-based. For example, given data of the shape:

```
{
  "type": "person",
  "name": "Bazbo",
  "nickname": "Baz",
  "age": "23"
}
```

...I personally would expect that I could load the data, add that node, then reload the app/data and not see "Baz" as a new option, thus being able to add them again. So rather than UUIDs, missing identifiers would be a hash of node content. If these are generated on import, I think it's 'just as good' as having pre-existing external UIDs; and allows the node to be recognized even after UI edits.

To prevent false negatives, we could allow the protocol to define which fields 'matter'; similar to how the two new roster generators exclude data results that match any existing ndoes with the same displayed fields.

Summary:

- For imported data without UIDs, content-hash-based UIDs allow the app to recognize data between reloads/imports
- For imported data without UIDs, generating those UIDs at import time fixes the observed problems in the app
- For new data, generate UUIDs

I'm sure this brings up as many problems as it solves, so, thoughts?

**Comment by wwqrd** [comment]
> To prevent false negatives, we could allow the protocol to define which fields 'matter'; similar to how the two new roster generators exclude data results that match any existing ndoes with the same displayed fields.

How about we attach the hash of the original "external data" object to a property of the new node when creating these in our network. That way we don't add any complexity to the protocol.

like:
```
{
  "type": "person",
  "name": "Bazbo",
  "source": "be7bb736839bbe2f0ea34d7dc668442c5db6dc23",
}
```

so:

- All nodes in network have a uid (uuid), that we generate.
- Researchers can add any esoteric properties, including an 'id' property that links to other research, but it could be anything, we don't use it in any way.
- We use hashes to link network nodes to any externally imported data.

**Comment by bryfox** [comment]
I think you're saying that we always generate a content hash, regardless of an existing [u]id key? I thought there might be a use case for allowing users to define UIDs since that's how it works now. For example, `{"name":"a","uid":1}` and `{"name":"a","group":"a","uid":1}` have different shapes because they're exported from different sources, but we know them to be the same.

(You called it "source" and I called it "uid"; if we don't respect that as a unique key coming in, what happens when that property already exists in external data? e.g., because it was from an export of a previous Network Canvas session?)

**Comment by rebeccamadsen** [comment]
So all nodes would have a `uid` that we generate when a node is added to the network (e.g. dragged over or clicked on), and external nodes would also have a `source` from the hash of pre-existing fields that is auto-inserted on import? There would no longer be a `uid` in external data itself?

The hash would be based off all fields then, and not just ones that are visible (e.g. in the Card view), right? That way nodes across the three NameGenerators would still match.

In that case, would both the `source` and the `uid` be able to help us distinguish uniqueness? I know the roster list needs a way to match nodes before they are officially in the network, so having a way to distinguish between nodes on import, not just when they are in the network, is important. 

@bryfox: That particular use case is interesting to think about, because what happens if the fields are overlapping but values are different? e.g. an address might have "Drive" or "Dr." which means the same thing but is different. We would just end up with whatever was loaded last, I think, which I'm not sure there is a way to do any better. They would have different hashes, though, so according to the hash comparison, they would be different.

**Comment by bryfox** [comment]
@rebeccamadsen that's a good example, and I think another argument for deferring to existing UID/source, or providing some mechanism to ignore spurious fields that shouldn't affect uniqueness. Working with any data set should be possible; working with the common cases should be easy.

**Comment by wwqrd** [comment]
Sorry I think there must be a new use case that's cropped up when I worked on this. The one I'm thinking about this in relation to is specifically the name generator.

Here we have two ways to create nodes, from the form, and cloning them from "external data".  The "external data" list is immutable.

So we need a way to determine which nodes in that list have been cloned, when our cloned versions might have changed since.

That looks could look like this, using hashes:

```
externalData: {
  listName: [
    // If we hash this object we get "be7bb736839bbe2f0ea34d7dc668442c5db6dc23"
    {
      "type": "person",
      "name": "Bazbo",
    }
  }
}

->

state: {
  network: {
    nodes: [
      {
        "type": "person",
        "name": "Bazbo",
        "source": "be7bb736839bbe2f0ea34d7dc668442c5db6dc23",
        ...
      },
      ...
    ]
  }
}
```

Generally speaking we also need a way to uniquely id any data in the network, that looks like this:

```
state: {
  network: {
    nodes: [
      // This node was generated from existingData, so *also* has a source property
      {
        "uid": "a975c295ddeab5b1a5323df92f61c4cc9fc88207",
        "type": "person",
        "name": "Bazbo",
        "source": "be7bb736839bbe2f0ea34d7dc668442c5db6dc23",
        ...
      },
      ...
    ]
  }
}
```

Researchers also might need to attach their own ids to nodes in existingData, that looks like this:

```
externalData: {
  listName: [
    // If we hash this object we get "70c073c651368e71383a200f849432f800f4452d"
    {
      "type": "person",
      "name": "Bazbo",
      "originalStudyId": 14,
      "followupStudyId": "janGroupBParticipant4",
    }
  }
}

->

state: {
  network: {
    nodes: [
      {
        "type": "person",
        "name": "Bazbo",
        "originalStudyId": 14,
        "followupStudyId": "janGroupBParticipant4",
        "source": "70c073c651368e71383a200f849432f800f4452d",
        ...
      },
      ...
    ]
  }
}
```

If I'm understanding correctly are you saying that this approach wouldn't work for the roster list?

**Comment by bryfox** [comment]
Ah, OK: both source and uid. Thanks for the example.

I don't understand the workflow that would cause the last step, which updates the already-imported `be7bb7` node content with `70c073`. (I had assumed that the source content hash was sufficient to determine uniqueness.) So while I don't follow how we know that "Bazbo 
 with followupStudyId" is the same as the original "Bazbo", the rest of it makes sense, and should fix the uniqueness issues. 👍 

In general, if I'm overcomplicating anything or introducing new use cases, please ignore me with haste; my mental model is mostly based on notes I took during early code reviews.

**Comment by wwqrd** [comment]
Not at all, I think the hash thing is a great idea. Are you saying that you'd generate the hash on load and use that as a uid, i.e. no source prop? I like the idea of keeping it simple with a single prop, but I think it could get awkward to figure out which nodes are imported and which are new.

Just to clarify on the above, the hashes are real ones (i.e. it's with those new id properties!), in practice since externalData never changes, neither would the hash.

I'm sorry, but having slept on it I'm starting to recall some of the history of this feature: I think there were some more constraints which is why this slightly convoluted uid & id situation came about in the first place.

I believe that researchers might specifically want to define _the_ `id` property, and that this __must__ be numeric, and that new nodes must also have an id, that is ideally contiguous, at least sequential. There was some talk about calculating this on export, which might be a better approach if we can ensure it's deterministic. This is why we have the `max(ids) + 1` id, which isn't guaranteed to be unique (because some of them are imported). Because of that I added uid, which should be guaranteed to be unique. In hindsight this was a bad call, and it probably would have made more sense to:
- __enforce unique ids on external data on load__
- __use sequential numeric ids for new nodes__

@jthrilly Perhaps you can clarify the above for us when you get back?

**Comment by jthrilly** [comment]
Really pleased to see the depth of discussion here between you all!

I think our approach to this should evolve to match the implementation strategy we have found works best for us over the past few months. 

Let's simplify this, down to the lowest common denominator feature set, and then add things only when they come up.

So:

- External data sources should not be assumed to have UIDs of any kind present within them. 
- UIDs for tracking the import of external data must therefore be generated by the app, on a per-interview session basis. This will likely require storing them in redux, and should happen on load. Remember we ultimately want to support external data loaded asynchronously. 
- Generating these by hashing is a neat idea, but we can bypass that complexity now and just generate UUIDs the old fashioned way.
- All other properties on external data nodes, should just be blindly copied to nodes added to the interview. This will give us an avenue for potentially allowing tracking of nodes between interviews (which is the complicated functionality).

**Comment by jthrilly** [comment]
Okay, I'm going to break this out into a new issue so we can review the design of externalData. 

For this issue: let's just fix the missing UIDs.
