### ISSUE TITLE
Teaching protocol: node bin sort order should be first in first out.

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#401]
The sort order for the node bin on the sociogram interface should be changed to "first in, first out".

**Comment by bryfox** [comment]
Network nodes are generally maintained in order, so this looks like a matter of removing "nodeBinSortOrder" from the teaching protocol file. (There are two sociograms, so I assume from both.)

Or is there something more to this?

**Comment by jthrilly** [comment]
Possibly not! I think previously we might have thought about using the sort order API and somehow sorting via node ID (if that is even still a thing after all the uuid discussion...). Whatever achieves the end result is fine.

**Comment by bryfox** [comment]
I was wrong; the sociogram selectors use a [default sort order](https://github.com/codaco/Network-Canvas/blob/master/src/selectors/sociogram.js#L77) if unspecified, so there's no clean way to fall through to the default ordering.

I don't see this documented either way in the wiki, but one option would be to remove that default sorting. (This would change the behavior of the development protocol as written.) If we want to keep that in place, we could define a way for a user to specify unsorted nodes. (Or, one could sort on a non-existent field without code changes...)

I don't think IDs help us here, and trying to build in order properties on node data itself (so that a user could sort on it) feels wrong. Any other ideas?

Removing the default sorting makes the most sense to me, but I'm not sure if that's required for another reason.

**Comment by rebeccamadsen** [comment]
I'm not sure what the best solution here is, but I can point to why there is a default sort order just to give perspective if we choose to change things now: https://github.com/codaco/Network-Canvas/issues/357. 

Would a timestamp on node creation help? I'm okay with changing the default sorting if that is best, just wanted to remind why it was done initially.

**Comment by bryfox** [comment]
Aha; thank you. I'll have to let @jthrilly decide how to proceed then.

If displayVariable is a better default, then the protocol needs some other way to express FIFO (or unsorted). `"nodeBinSortOrder": "fifo"` [preset], `"nodeBinSortOrder": { "*": "asc" }` [non-existent field], `"nodeBinSortOrder": { "addedToNetworkAt": "asc" }` [after adding a timestamp to nodes]...

Timestamps of when nodes are added to a network would work. The reasons it felt wrong: it adds another property to data (which, if I understand the current flow, would get exported); it requires users to name that internal property name correctly; and (for this issue) we already have the information we need without this addition.

**Comment by jthrilly** [comment]
Okay, so I think given that `network.nodes` is an array of objects, and that we only ever append to it, we can get a naive version of what we want just using the implicit ordering provided by the array index. No need for an additional property. 

We can then add a special case for the sorting api as Bryan suggests: `"nodeBinSortOrder": { "*": "asc" }`

When the asterisk is given as the sort parameter, we will sort by the array index.
