### ISSUE TITLE
Support multiple in-progress interviews

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#414]
We need to be able to support resuming interviews, as well as starting a new interview while another one is in progress (irrespective of protocol). 

To facilitate this, we will need to change the structure of the redux store to look like the following:

``` JavaScript
{
  errors: {},
  menu: {},
  modals: {},
  protocol: {},
  search: {},
  sessions: {
    235235: { // an automatically generated session UID
      protocol: "demo.canvas", // A pointer to the protocol to be loaded
      network: [], 
      prompt: {}, 
      stage: {}
    } 
  },
  session:  235235, // A pointer to the currently loaded session to be used by other parts of the app.
}


```

The UI for resuming in progress interviews is present in #388.

**Comment by wwqrd** [comment]
👍

**Comment by rebeccamadsen** [comment]
With #411, the redux looks like it will be changing and would have an impact on this. Instead of having stage index in redux, we have a router object with a pathname. The stage index and protocol name can be derived from the router pathname, so I think a session object here would need the router url and not need the protocol or stage information.

Aren't prompts also loaded when the protocol is loaded? I'm not sure we need that in a session object either. I think a session object would just need the router pathname and the network.

**Comment by rebeccamadsen** [comment]
Are we keeping track of which prompt was left off for this issue, so we can restore the exact prompt?

Do we need a way to "forget" a session and not track it any longer? I know the current start screen is going to be reconfigured, so perhaps that is a better place to ask that question.

Will each protocol have an indefinite number of sessions possible? Again, that may be a "start" screen issue.

I'm debating whether it makes sense to simplify the router, and route to something like "/session/:id" and get the protocol id, protocol type, and stage id from redux. Otherwise I think we'd need something like "/session/:sessionId/:protocolId/:stageIndex" (and store the pathname in the session object in redux), which is long but might offer more flexibility to us in development.

**Comment by jthrilly** [comment]
> Are we keeping track of which prompt was left off for this issue, so we can restore the exact prompt?

It would be great to keep track of the prompt too.

> Do we need a way to "forget" a session and not track it any longer? I know the current start screen is going to be reconfigured, so perhaps that is a better place to ask that question.

We do have a UI for this, but it isn't yet in the mockups. You are right that it is part of the new start screen.

> Will each protocol have an indefinite number of sessions possible? Again, that may be a "start" screen issue.

Yes, although there will be limits to this which we will want to discover. I think right now we are persisting our redux store using a different mechanism depending on the platform. I don't know what the size limits for that data are.

> I'm debating whether it makes sense to simplify the router, and route to something like "/session/:id" and get the protocol id, protocol type, and stage id from redux. Otherwise I think we'd need something like "/session/:sessionId/:protocolId/:stageIndex" (and store the pathname in the session object in redux), which is long but might offer more flexibility to us in development.

The latter option looks like the winner, given the above!
