### ISSUE TITLE
Font sizing for names - tweaking request

### ISSUE THREAD

**Issue by berniehogan** [codaco/Network-Canvas#434]
The font sizing for names currently is too small for narrow width characters. 

For example, illani would very tiny, whereas robbie would be comfortable. We should consider n characters and have the widest possible characters be closer to the edge so that narrow characters are more readable.

**Comment by jthrilly** [comment]
Just to add to this that nodes on the sociogram need to be slightly smaller. Make this change as part of this feature to ensure harmonisation.

**Comment by rebeccamadsen** [comment]
Is this more of a typography question? As in, our font choice determines the width of each individual character? I know there are things like font-kerning and letter-spacing and word-spacing, but spacing for narrow vs wide characters I thought was up to the font?

**Comment by jthrilly** [comment]
> Is this more of a typography question? As in, our font choice determines the width of each individual character? I know there are things like font-kerning and letter-spacing and word-spacing, but spacing for narrow vs wide characters I thought was up to the font?

Seems to be, yes. I thought this issue was about improving sizing on some medium length names bu increasing it. The system right now works by setting a specific font size for each length of label. We moved to this from a system where we calculated the maximum possible size of label for each individually, which was too computationally expensive. 

@bryfox - just a crazy thought, but do you think `labelFontSize` could be another derived property calculated in a worker, and then cached until label changes?

**Comment by bryfox** [comment]
I assume you're referring to the [sandboxed workers](https://github.com/codaco/Network-Canvas/pull/613), which I think are better reserved for user code. I can't imagine the overhead would be less than calculating the appropriate width based on contents in this case.

If that calculation is too expensive, then maybe we could improve the heuristic a bit. Score the word by summing relative letter scores based on width (M=5, I=1, ... or something) and bucket into the same font sizes, instead of using char count directly.

It looks like the old system you're referring to is still in the code as `scaleTextToFit`, which could be improved somewhat if that's preferable. For example, to get the same size resolution as the current approach, we'd only need 7 iterations (max), instead of starting at 0.

**Comment by rebeccamadsen** [comment]
Bucketing based on font sizes still seems like a typography issue. Is there a better font that handles letter spacing to our liking that we wouldn't need to modify like this?

**Comment by bryfox** [comment]
Maybe I'm misunderstanding, but I thought it was the other way around — we want to adjust font size, not letter spacing based on font size. Right now, we assign `iii iii` a small font-size, but `M M` a big one, even though we'd expect the latter to take up as much or more space. Unless we used a monospace font, setting based on length will have that issue.

**Comment by jthrilly** [comment]
> Maybe I'm misunderstanding, but I thought it was the other way around — we want to adjust font size, not letter spacing based on font size. Right now, we assign iii iii a small font-size, but M M a big one, even though we'd expect the latter to take up as much or more space. Unless we used a monospace font, setting based on length will have that issue.

You're correct. 

> Bucketing based on font sizes still seems like a typography issue. Is there a better font that handles letter spacing to our liking that we wouldn't need to modify like this?

At this stage, I don't think we can change the font - it is pretty integral to our branding. 

> It looks like the old system you're referring to is still in the code as scaleTextToFit, which could be improved somewhat if that's preferable. For example, to get the same size resolution as the current approach, we'd only need 7 iterations (max), instead of starting at 0.

I think the issue we had previously was that performance was terrible due to re-rendering causing the app to be re-calculating the font size too often. It seems like we've got a better handle on that now, so coupled with your suggestion of a more efficient system, we might be able to give this a go. 

Would we be able to set this up to work with the label function? That is, calculated when the label changes/is set? How would this work with external data? Would the label and font size be calculated when the data is loaded, or when the node component is rendered?

The other thing I really like about your suggestion is that we might be able to better handle emoji, which are 2 chars "long" (`str.length`), but don't take up width proportionally. That would be a cool win.

> I assume you're referring to the sandboxed workers, which I think are better reserved for user code. I can't imagine the overhead would be less than calculating the appropriate width based on contents in this case.

Reason I brought up workers is I am conscious of thread blocking, particularly on mobile, where I believe we are still limited to one thread. I might be mistaken, but I had assumed using workers might let us parallelize. Was just a passing thought, and doesn't really impact this discussion.

**Comment by bryfox** [comment]
> Would we be able to set this up to work with the label function?

Yes. As of that branch, the node container is responsible for determining its label text. It renders a ui/Node component, which is responsible for setting the length className. (The latter is already happening on master; there are no conflict worries.) I think the UI node is a natural place to keep the sizing logic.

> workers

In general, yes — we could use worker threads for long-running tasks; they're supported on all platforms we need.

**Comment by rebeccamadsen** [comment]
How would we create the buckets for character width? And would this scale to international characters?

**Comment by jthrilly** [comment]
Good question! I just had a look, and it seems Quicksand supports all extended latin characters. I don't think we have a plan for non Latin alphabet at this point.
