### ISSUE TITLE
node field/prop collisions

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#446]
Since we use the spread operator to include all the fields in a node or `EnhancedNode` _after_ our props (in most or all cases?), it is possible we could have unintended collisions and clobbering of network canvas functionality. Some overriding of props is likely intentional (e.g. `label`, `color`, `selected`). Some is decidely not (e.g. `meta`, `onSelected`, `allowDrag`). Which is which is up for discussion.

This is related to our [uid discussion](https://github.com/codaco/Network-Canvas/issues/415). See the conversation [here](https://github.com/codaco/Network-Canvas/pull/443#issuecomment-381155177), with one idea being to prepend special props with an underscore.

**Comment by wwqrd** [comment]
This configurations allows you to override default properties. In cases where we don't want to do that we can change the position of the spread operator:

```jsx
<EnhancedNode
  {...props}
  label="Non overridable field"
/>
```

Or in cases where we want to exclude specific properties from the component:

```jsx
const foo = ({ dontIncludeThis, orThis, ...rest }) => (
  <EnhancedNode
    {...rest}
  />
);
```

**Comment by jthrilly** [comment]
I think reordering will work. @rebeccamadsen ?

**Comment by rebeccamadsen** [comment]
I think reordering is part of the solution. It would ensure the user can't override our system created props and cause a crash or otherwise adversely affect functionality of the app; it protects us. But without the documentation to warn a user which fields we are using, wouldn't we still run the risk of clobbering their data? It's a two way clobbering. Maybe they have their own use for a 'meta' field just as much as we do?

**Comment by jthrilly** [comment]
I think I am still in favor of our "special" properties having some kind of pattern to them. Either nc_prop or just _prop.

@wwqrd - this seems like the sort of suggestion you would hate. Can you think of a better way?

**Comment by bryfox** [comment]
I'm trying to understand the reason for spreading external data props into view components, rather than keeping things contained in something like a `sourceData` prop. With the node example:

- What view properties are we intending users to customize directly via externalData? Labels, for example, have a different mechanism (`displayLabel`).
- Should 'special' props (including uid) be exported with data? Currently, the export merges view information (like stageId) into the Node data (which I assume is intentional); put another way, is the merging of app & user data required?
- Can a user export data from the app, and source that as external data for another interview? (If so, does that make special naming (`nc_*`) an incomplete solution for this problem?)

I'm sure there are good answers to these, and we can't just move external data into a containing prop to solve the issue. Hopefully we can document the answers somewhere permanent (possibly wiki); a better understanding of the expected data flows would if nothing else help me during development & testing.

**Comment by wwqrd** [comment]
Is there any reason we can't just be explicit with props at the point of use? We know that Node only takes x, y, z parameters, so we don't need to pass it anything and everything from the source data in the first place.:

```jsx

render() {
  return nodes.map(
    ({ name }) => (<EnhancedNode onClick={() => this.clickHandler()} name={name} />),
  );
}
```

This way it's going to be clear if props are going to clash, at which point maybe it's a decision about better names for HOC props.

******

The pattern arises out of the use of HOCs:

```jsx
const Node = ({ name }) => (<div>{name}</div>);

const ComponentWithOnClick = (WrappedComponent) =>
  ({ onClick, ...rest }) => (<WrappedComponent onClick={onClick} {...rest} />);

const EnhancedNode = ComponentWithOnClick(Node);

...

render() {
  return nodes.map(
    node => (<EnhancedNode onClick={() => this.clickHandler()} {...node} />),
  );
}
```

if we group all those props with a name we get:

```jsx
const Node = ({ node }) => (<div>{node.name}</div>);

const EnhancedNode = ComponentWithOnClick(Node);

...

render() {
  return nodes.map(
    node => (<EnhancedNode onClick={() => this.clickHandler()} node={node} />),
  );
}
```

or:

```jsx
const Node = ({ name }) => (<div>{name}</div>);

const NodeWithOnClick = (Node) =>
  ({ onClick, node }) => (<Node onClick={onClick} {...node />);

const PanelWithOnClick = (Panel) =>
  ({ onClick, panel }) => (<Panel onClick={onClick} {...panel} />);

...

const EnhancedNode = NodeWithOnClick(Node);

...

render() {
  return nodes.map(
    node => (<EnhancedNode onClick={() => this.clickHandler()} node={node} />),
  );
}
```
