### ISSUE TITLE
On Sociogram, screen can be navigated away from without all nodes being placed

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#463]
On Sociogram, screen can be navigated away from without all nodes being placed.

Are we planning to handle this with skip logic? Or should we maybe add a setting to the Sociogram interface?

**Comment by jthrilly** [comment]
Just repeating what I put in slack for anyone who comes across this:

Currently we don't impose requirements on the _stage task_ the same way we might on a smaller interaction within the stage. For example, we don't require that a user create a node on a name generator before the interview can progress, but we _can_ require that any node that they do create contain a given field. Similarly, we don't require the participant to perform the layout step.

This is because we have thus far depended on the interviewer to manage the progress through the interview, and have preferred the flexibility to be able to move freely between stages (for example, when returning to a previous point while in the middle of a task, to edit or add data). Enforcing logic here would prevent that.

There are some issues unique to this interface though: 
- Subsequent sociogram tasks might depend on a layout of some kind
- A participant may not with to lay out a specific node, but the node stack prevents other nodes from being laid out unless the top node is moved. This relates to a broader question: should the sociogram contain a "not sure" or "don't want to answer" bin? We discussed this in Chicago recently, and decided against this.
