### ISSUE TITLE
on NameGeneratorList (desktop), when the window is portrait (?) then the prompt covers the filter controls.

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#465]
on NameGeneratorList (desktop), when the window is portrait (?) then the prompt covers the filter controls rendering them unusable.

**Comment by jthrilly** [comment]
Do you mean actual portrait orientation for a device? Height greater than width? If so, this isn't a supported orientation. With that said, we should probably do better with this, because a particularly long prompt might cause the same issue.

**Comment by wwqrd** [comment]
I mean on Electron when height is greater than width. Are we planning to force this as a fullscreen app then?

**Comment by rebeccamadsen** [comment]
Restricting aspect ratio would probably help, but I agree we ought to also check whether a long prompt has the same issue.

**Comment by bryfox** [comment]
Long prompts currently overflow the container, potentially bleeding over both the prompt pips and content below. Mouse/touch events are captured on that layer. (We could set an overflow to constrain that, but prompt text is probably critical to read without scrolling.)

I think setting a `position` (stacking context) on the main content would make sense, so that prompt text is always visible, but prompt swiping/clicking is constrained to the top 200px.

**Comment by bryfox** [comment]
I opened #516 to fix the control (click) issue. If we want to control prompt overflow or have variable-height prompts, I can add to that PR.

I think aspect ratio is a separate issue, and [may only be supported on macOS](https://electronjs.org/docs/api/browser-window#winsetaspectratioaspectratio-extrasize-macos)?
