### ISSUE TITLE
Using the arrow keys to navigate a radio group causes an error

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#485]
If you navigate within a radio group and go beyond the range of options, you get an error.

<img width="1057" alt="screen shot 2018-05-02 at 3 37 07 pm" src="https://user-images.githubusercontent.com/1387940/39529488-b837e006-4e1e-11e8-8d8e-9f1452faa740.png">

**Comment by bryfox** [comment]
There seem to be a few issues here, as RadioGroup supports rendering children via `options` or `children`:
- If the 'options' version of RadioGroup is used (as in the factory protocol), then the keyboard handler errors on any arrow/enter keypress, regardless of index
- If the 'children' version of RadioGroup is used, then the error happens with out-of-bounds accesses as described above
- RadioGroup allows arbitrary children (not just RadioInputs), but no checks are made in the handler about the types of children being accessed

I can add checks to the keyboard handler; however, I think the better fix is to remove manual keyboard handling entirely, since keyboard navigation works natively, and the event passing seems to only cover partial cases. From what I saw: a client of `<RadioGroup>` must pass both `onChange` and `onRadioClick` (the latter fires on any radio change); the keyboard hander passes radio changes to the top-level change handler, but *only* for keyboard events. Is there a use case to support that behavior?

It seems like we should be able to duplicate those events for any radio change (keyboard or click), if needed, or remove the duplicate event passing entirely, since a client is required to implement both anyway. Or even remove the need for multiple handlers for radio & radio group.

Any of these changes would support the existing use case I see in the Factory Protocol, but would change the public interface to some degree, so I'll need input from the team here.

**Comment by wwqrd** [comment]
I would expect standard keyboard bindings to work for this input? Maybe we should get that working and remove this?

@bryfox I wonder if we need both options, maybe we should stick with one type of interface?

**Comment by bryfox** [comment]
Standard keyboard bindings work right now (in that keyboard moves focus and change event fires on the radio inputs); no handler needed. The handler is forwarding "radio click" (i.e., change) events to the other change handler, if children interface is used.

@wwqrd If we remove support for the 'children' interface, it's not clear on whether I should start forwarding events for the 'options' interface, or just remove the handler. I don't know what the use case is for that, so I was proposing one of (1) removing the forwarding, (2) forwarding on any change event, not just keyboard, or (3) taking only a single change handler to radio group.

**Comment by wwqrd** [comment]
For event handlers in all of those cases, we should probably look to take the lead from redux-form's <Field /> ultimately expects to see? I know we're using an adapter currently for input components, but maybe that could be slimmed down eventually.

If the normal keyboard shortcuts work then, like you say, we should check whether it's got an intended use case.

**Comment by bryfox** [comment]
A rewrite of input components is happening in [feature/new-inputs](https://github.com/codaco/Network-Canvas/tree/feature/new-inputs); any changes should happen based on that.

**Comment by rebeccamadsen** [comment]
I think this has been resolved with the new inputs refactor, or at least I can't duplicate this.
