### ISSUE TITLE
Scrollable 2.0

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#548]
Enhance the scrollable behavior and styles to support a horizontally scrolling container. I would like to use this in the ordinal bin bucket.

Would this be a useful extension?

**Comment by rebeccamadsen** [comment]
Would this be an either/or kind of behavior, or possibly allow both to happen in the same container?

**Comment by jthrilly** [comment]
Either/or, I think

**Comment by bryfox** [comment]
See also https://github.com/codaco/Network-Canvas-UI/issues/55, where we'd talked about having fundamental scrolling behavior as part of UI.

**Comment by bryfox** [comment]
This might be a good time to evaluate performance of the current scroller as well. I made some minor improvements to node lists specifically in #623, but with a large node count, performance is still pretty poor.

It seems like the crux of `scrollable` is to add a 20% high gradient mask when its scrollTop is > 0. (The bottom gradient is always there and of a fixed height.)

Would we consider changing that top gradient to a fixed height, equal to the top padding of the scrolled content so that it was automatically visible once scrolling started? It's not quite the same effect, but it took my performance measurements on master for a 200-node list from ~5fps to ~60fps — just by removing [a few lines](https://github.com/codaco/Network-Canvas/blob/master/src/behaviours/scrollable.js#L29-L31)).

If that's not doable, maybe it's worth seeing how implementing this outside React would fare.

I'm sure there are other component optimizations to make, but those will mostly be in wrapped components, and it doesn't feel like scrolling should come with this heavy a built-in cost.

**Comment by jthrilly** [comment]
Would you mind showing a side by side of the change in look? Or is it negligible? Frankly, for those performance gains, I think it would have to be pretty hideous to not be an improvement. Perhaps even go straight to a PR for review if the change is so small.

**Comment by bryfox** [comment]
I pushed a prototype up to `prototype/static-scrollable`; it might be worth comparing there.

Here's a side-by-side using 200 nodes.

| master | static-scrollable |
| - | - |
| ![mastersmall](https://user-images.githubusercontent.com/39674/43597540-63deed22-9650-11e8-80f0-28d46359d65e.gif) | ![static-scroll-small](https://user-images.githubusercontent.com/39674/43597541-63ebda78-9650-11e8-8119-92bb5334e28f.gif) |

The main differences in the look of static-scrollable:
1. uses a fixed-height gradient on the top, unlike master. (So the difference will be exaggerated, the taller the scrollable is.)
2. The gradient is always visible (i.e., the content is masked), as described above; need to ensure padding in the child content.
3. The gradient doesn't "snap" in/out of view as it does sometimes on master (depending on the debounce timing)

We'd need to deal with the padding issue (#2) beyond this prototype. We could address this in CSS, or probably handle it dynamically after the scrollable component mounts.

**Comment by jthrilly** [comment]
Looks fantastic, and the performance improvement is indeed incredible. Nice work Bryan!

On the padding issue, let's just handle it in CSS. Can you PR your prototype branch when that change has been made?
