### ISSUE TITLE
Resume Interview 2.0

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#550]
Enhancements to the "resume interview" screen:

- [x] Proper styling of cards
- [x] Sorting and filtering by useful criteria (protocol, last modified, network size?). This work should be compatible with #549
- [x] Long press to select multiple interviews, as a means to export.
- [x] Drag to bin in order to delete

**Comment by bryfox** [comment]
Depending how we want to handle export of multiple interviews, we may need an additional issue to support large file uploads over https.

**Comment by jthrilly** [comment]
> Depending how we want to handle export of multiple interviews, we may need an additional issue to support large file uploads over https.

What do you see as "large"? Given that interview data will be limited to JSON (no binary data), and that we are also probably facing quite aggressive RAM and app storage limits (which are as yet uncharted), I think we should expect 100% of interview payloads to be < 1mb, and 99% to be smaller than 500kb, with a mean of around 200kb.

If this is large, what special support do we need to add? Might be easiest if you go ahead and create the issue and link it here so it is ready for someone to pick up.

**Comment by bryfox** [comment]
If uploading via a cordova plugin, I think the bottleneck is serialization into the native side. The hard limit seemed to be on the order of megabytes, but soft limits for UX are possibly lower. I don't expect a single export to be a problem. If we want to upload a single larger batch, we could do so via disk, or use an auth mechanism other than client-side certs so that we can upload using XHR.
