### ISSUE TITLE
Prevent or clean up invalid sessions

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#569]
Currently, 'zombie' sessions are created when importing an invalid protocol; they can never be resumed since there's no associated session. Ideally, a user would not have to manually clean up.

Update: With updates to redux actions, need to also ensure this is fixed for failed downloads (as mentioned in #571).

Related to #568: if session creation is decoupled from protocol loading, then these should be cleaned up. If sessions are created after their protocols are validated, this will be prevented.

**Comment by rebeccamadsen** [comment]
Another side effect of the zombie sessions is that you can add mock nodes to a zombie session just after creation; the menu item shows up. I don't think it's worth making this a separate issue, though, because not being able to create zombie sessions would eliminate the issue of adding mock nodes to a zombie session.

**Comment by jthrilly** [comment]
This was resolved by changes to protocol import.
