### ISSUE TITLE
Ego form interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#584]
An interface that displays an arbitrary form, where the values of the form are assigned to the ego node.

**Comment by bryfox** [comment]
See the `isEgo` comment in [#583](https://github.com/codaco/Network-Canvas/issues/583#issuecomment-429372117), and also https://github.com/codaco/networkQuery/issues/3. If an `isEgo` attribute will have special meaning for network queries, we'll need to document it.

**Comment by jthrilly** [comment]
Just for clarification, the `isEgo` property is intended as a workaround for researchers to use to manage situations where, in a roster study, ego is contained in the roster and must be excluded from certain prompts/panels/bins.

The current plan is that Ego will actually be modelled in a separate part of the network model. Most likely `network.ego`. This interface will assign data there. 

If we encounter unforeseen issues with that design, we can look at modelling ego within `network.nodes` as a protected type somehow.

**Comment by rebeccamadsen** [comment]
This feels kind of like the per-alter form interface, but many forms to one node instead of one form to many nodes... If we want multiple "screens", I'm preferring a list of forms; we could alternately change the structure of forms themselves but I think that's overly complicated. Here's a first go at an API for the protocol, although I have some questions to go along with it:

```
    {
      "id": "ego-form-1",
      "type": "EgoForm",
      "label": "Ego Form",
      "forms": [
            "myEgoFormID1",
            "myEgoFormID2",
            "myEgoFormID3"
      ]
    }
```

* Will this need an "introduction" type panel a la per-alter form interface, or a header that remains constant, or a header that changes as forms progress, or will the forms be self descriptive?
* It could be nice to have a visual indication on each prompt/screen that this all relates to a "You" node if there's no header. If so, is "You" an acceptable label for a node, or is that something people may want to customize?
* Will multiple "ego form" interfaces in one protocol be allowed? As in, the first one may create the ego node, but additional occurrences could update the ego node?
* Where will the ego node be used, after it is created?
* Will we need to change other interfaces to support or add ego?
* I assume this affects export. Do we know what changes to export will need to happen?
* Does an ego have an inferred `subject` with entity `node` and a `type` like other nodes?
* If we allow multiple forms, do we enforce they all have the same `type` and `entity`, or does that mean `subject` needs to be specified for the ego interface independent of forms?

**Comment by jthrilly** [comment]
Sorry for only just seeing this @rebeccamadsen!

> This feels kind of like the per-alter form interface, but many forms to one node instead of one form to many nodes... I

This is exactly the idea. I think the idea would be to have form components automatically split over multiple screens, although that might be difficult given there is no way to detect their size. 

As a starting point, I think you should go with one screen per form for ego. So, to have multiple screens, you would have multiple forms.

Otherwise, this should just be identical to the ego form interface.

> * Will this need an "introduction" type panel a la per-alter form interface, or a header that remains constant, or a header that changes as forms progress, or will the forms be self descriptive?

This will use the intro type panel from alter form. No need to use the form name anywhere for now.

> * It could be nice to have a visual indication on each prompt/screen that this all relates to a "You" node if there's no header. If so, is "You" an acceptable label for a node, or is that something people may want to customize?

You is an acceptable starting point. yes. Although I don't think we actually need a node representation for the participant.

> * Will multiple "ego form" interfaces in one protocol be allowed? As in, the first one may create the ego node, but additional occurrences could update the ego node?

Yes

> * Where will the ego node be used, after it is created?

Nowhere for now, except export.

> * Will we need to change other interfaces to support or add ego?

No.

> * I assume this affects export. Do we know what changes to export will need to happen?

Yes, but I will handle this.

> * Does an ego have an inferred `subject` with entity `node` and a `type` like other nodes? Or should it be entity `ego`? Would it still have a `type`, or are ego variables all lumped together?

This is a great question. I don't think ego should be part of the network model, which is `nodes` and `edges`. In that sense, `subject` doesn't apply to ego. There is only one ego interface, and so this is implicit.
