### ISSUE TITLE
Node labels in chrome

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#627]
The node labels on the education protocol are blank on Chrome, but are working fine on Android and electron. Node labels for the development protocol seem fine in Chrome.

**Comment by bryfox** [comment]
Underlying issue: a syntax error in a worker script is caught, but the error state is not communicated to the Node component. (This manifests in Chrome because the dev-server there returns the contents of index.html for the blob.)

This needs to be handled as a more general failure state (rather than a per-Node error), since we won't have message IDs available in the WorkerAgent. i.e., we can't use the normal promise rejection flow. Either the Node needs to check for a general error state on its agent, or there needs to be a separate notification mechanism.
