### ISSUE TITLE
Use of large assets in protocols exhausts memory (Cordova)

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#681]
Some iOS devices are having issues with the Video interface screen in the development protocol.

The browser page reloads during (or before) playback, or the app may crash. 

- Instrumented Memory use seems stable and not unusually high
- Safari can play video without issue on a standalone test page

**Comment by bryfox** [comment]
On Cordova, we're not streaming video; it's being loaded into memory and then read as a data URL. I don't think there are any CSP concerns here, so we can update to render video, audio, and img with existing URLs on disk.

**Comment by bryfox** [comment]
I tried to implement streaming on iOS† following the Cordova file plugin documentation, but those techniques only work with UIWebView; in the end we're blocked by additional restrictions from WKWebView.

In short, streaming factory protocol assets on iOS is easily fixable, but streaming user-provided assets is much less straightforward. This [bug report](https://bugs.webkit.org/show_bug.cgi?id=154916) covers it; the author of that report [has a good overview](https://www.construct.net/blogs/ashleys-blog-2/hacking-something-useful-out-of-wkwebview-932) of the issue & workarounds.

Potential steps forward (with less-favorable options striked):
- Run a local webserver on iOS, and deal with ensuing security issues
- Copying assets to a tmp [or other] dir on demand is supposed to work, at least for now?
- Place size limits on assets [would be severe for video], at least on iOS
  - possible that we can reduce the current limit with blobs in favor of base64 encoding
- <strike>Implement the new WKWebview hooks.</strike> Still requires copying data, and I don't think would really solve our problem.
- <strike>Use UIWebserver</strike>. It's deprecated, slow, and would require significant changes elsewhere.

†Android might work fine with the standard approaches; I haven't gotten there.

**Comment by jthrilly** [comment]
Thanks for the great research Bryan. 

I read the threads you linked. Seems like local webserver or temp assets copying are the way forward, since we can't have crashing happening (aside: I am still not sure why exactly our current code is causing a reload/app crash...seems to be a bug in its own right, since there aren't documented limits I can find, and there is no meaningful debug information that is capturable for me either). 

I see on the webkit bug tracker that a few people are having issues with getting a local webserver up and running. I also note the relatively fresh issue for cordova-ios, which might provide a more stable long term solution.

With those in mind, I would be inclined to try implementing copying protocol assets to the temp folder (on installation?), and having a separate codepath for cordova iOS. What do others think?

**Comment by jthrilly** [comment]
Just one other thing: am I correct in thinking that this issue doesn't exist (as far as we know) on android?

**Comment by bryfox** [comment]
> seems to be a bug in its own right

Right; the real problem here is 'just' high memory use. I don't see an app crash, just the page reload. I imagine webview tries to deal with the memory pressure by doing that reload. I would also imagine if that doesn't happen fast enough the OS would kill the app after a memory warning. As far as I can tell, I'm not hitting any hard limits (documented or otherwise) on my device.

> android

On Android, I'm hoping the streaming approach will work fine; i.e., providing a filesystem URL or path to the video/audio/img tag. That remains to be seen. As it is now (on master), the best case is that it'll be very slow to load, but something large enough will eventually crash or similar. That'll vary by device & resource use.

**Comment by bryfox** [comment]
> copying protocol assets to the temp folder

This would probably need to happen [repeatedly] on launch, protocol load, or screen load. I'm not sure how long we can count on that approach to work.

> fresh issue for cordova-ios

Thanks for pointing that out. Looks like the issue is to support `WKURLSchemeHandler` for iOS 11+, which is what I described as "the new WKWebview hooks". I just re-read the API docs, and I think I was wrong — it looks like this would support streaming and work nicely for our use case.

I think this is the approach that makes sense to investigate first. It's certainly preferable to the local webserver.

**Comment by jthrilly** [comment]
So just to be clear: 

- you _don't_ think we should implement temp folder copying as a short term fix, because it would have to run on protocol load (and therefore perform slowly), and might be fragile otherwise
- you think we _should_ wait for `WKURLSchemeHandler` in cordova-ios (issue here: https://github.com/apache/cordova-ios/issues/415)

FWIW, I don't think temp folder copying would be the worst idea. We have a UI flow for handling delays loading a protocol (the spinner), and I don't see a deliberate changing breaking this before cordova-ios is updated. That's the other thing - cordova-ios may move very slowly, or not at all, and we do need to resolve this either way before release.

**Comment by bryfox** [comment]
I think `WKURLSchemeHandler` is the better approach. We don't need to wait for cordova-ios support to implement it. I'm not too worried about slowness of the temp approach; I am worried that it could stop working at any future OS release.

On the other hand, copying to a temp directory is probably lower-touch, so we could try that first and hope that a cordova-ios update makes the scheme handler approach viable from JS at some point.

**Comment by jthrilly** [comment]
> On the other hand, copying to a temp directory is probably lower-touch, so we could try that first and hope that a cordova-ios update makes the scheme handler approach viable from JS at some point.

That was my thinking. I had assumed implementing the url scheme handler ourselves would be more difficult. Either way, seems we have a consensus.

**Comment by bryfox** [comment]
I pushed up a branch containing the tmp directory hack for iOS: [fix/download-asset-url](https://github.com/codaco/Network-Canvas/tree/fix/download-asset-url).

On an iPad Air, iOS 12.0.1, the video does not play (error loading resource). On an iPad Pro, iOS 11.4.1, the tmp hack works. (It also works on Simulators running iOS 12, but I don't think we can trust that in this case.)

My suspicion is that this no longer works in iOS 12, but would be good to hear if anyone can confirm.

**Comment by jthrilly** [comment]
I tested this. Results:

- iOS 10.3.1 iPad Pro sim, video played
- iOS 11.4 iPad Pro sim, video played
- iOS 12.0 iPad Pro sim, video played

- iOS 12 iPad Air sim, video played

- iPad Pro on iOS 12.0.1, video played

Since this worked on a physical device running iOS 12, I'm reluctant to say that it has stopped working in iOS 12. It doesn't seem likely that iOS would behave differently on your Air and my Pro on the same version, but it is possible.

At the moment, we have it working across the board except on your Air. I will try and get access to more test devices (I have a mini somewhere) to see if we can narrow this down. 

Do you think it would be better to start work on `WKURLSchemeHandler`?

**Comment by bryfox** [comment]
Interesting. I agree my earlier iOS 12 hunch is wrong. I'll test on my device again and give a closer look to the actual error I was seeing. I'll also try to find a couple of other test devices. Would be great to use the tmpdir workaround for now if we can.

**Comment by bryfox** [comment]
The difference was file size, and the problem was during copy phase. Because of #754, I'd been reloading to test, and never realized the problem; if the file is large enough, the copy fails and I wind up with a 0-byte file in the temp dir. I'll fix the file copy and add a size check when loading.
