### ISSUE TITLE
Support Timestamp component for data creation?

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#700]
The last example in the [forms documentation](https://github.com/codaco/Network-Canvas/wiki/protocol.json#forms) is for a hidden field that takes on a value as a result of an evaluated expression. The development protocol contains similar examples; all of them are for timestamping record creation.

Supporting timestamps seems straightforward; I don't see arbitrary expressions listed elsewhere as a [use case](https://github.com/codaco/Network-Canvas/issues/472#issuecomment-384631182). (I'd be wary of having user scripts populate hidden values that are never seen or verified until data export.)

**Comment by jthrilly** [comment]
The intention here was to have derived and calculated values (based either on network data or more general information, such as time, date, etc.) be possible at node creation time. There are limited use-cases, but for those situations arbitrary expressions were the only real option, since the specifics were so varied. This is definitely more of advanced feature, rather than part of the core functionality.

What I had hoped was that we might be able to extend the secure worker concept to any and all areas of arbitrary evaluation. The api for this feature might therefore change so that a hidden form field "value" is set to the location of the worker. Ultimately, it would be great to be able to have a consistent way to use workers for secure derived/arbitrary evaluation wherever needed in the protocol, with a consistent and "safe" api.

If this seems possible at least in theory, I think the functionality itself can be omitted for now. Perhaps update the documentation to reflect the intention to support this in the future.

The hidden input type in a form with a conventional predetermined value is something we do want to keep.

**Comment by bryfox** [comment]
Got it. It is possible to use workers for this.

Node creation will then be need to be asynchronous, so we'll need to rework that flow. If it's only for creation, we'll also need to take care that this isn't happening on node edit (i.e., we can't always include the 'hidden' field as in the previous examples).

I've updated the [documentation](https://github.com/codaco/Network-Canvas/wiki/protocol.json#forms) with this info (including static hidden fields). It doesn't sound like specific timestamped components are needed then, so I'll close this.
