### ISSUE TITLE
Checkbox on form not positioned well

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#724]
On the mobile form in the development protocol, one of the fields is a checkbox, not in a group. It's called "A checkbox" on "Test for form input controls". It is not positioned nicely. Possibly checkboxes ought not to be used independent of a group, or possibly this just needs some nicer css.

![checkbox](https://user-images.githubusercontent.com/16093053/46895815-1334e180-ce48-11e8-9bcb-20f3b19efdd3.png)

**Comment by bryfox** [comment]
Looks like this was improved with the scaling viewport changes:

<img width="558" alt="fullscreen" src="https://user-images.githubusercontent.com/39674/48729022-934b2580-ec04-11e8-9deb-bd4f7dd8e19a.png">

**Comment by jthrilly** [comment]
I think a single checkbox might be a bad design pattern for most of our use-cases, and the toggle will be more appropriate. Because of that, I built the checkbox styling to assume that it would always be in a group, and therefore always inside the form-field-container parent div.

If that's not the case, we should probably address this by having a modifier class that adds the required styling, and is enabled with an optional property passed to the component.

**Comment by rebeccamadsen** [comment]
The styling looks to be improved right now. I agree a single checkbox is a bad design pattern, but since we allow it, we can at least make sure it isn't a completely jarring experience. I'm fine with how it looks now.

**Comment by jthrilly** [comment]
Sounds good.
