### ISSUE TITLE
Exporter fails when layout variable is left blank

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#849]
If a node is not assigned `{ x, y }` positions for a layout variable then the exporter will fail when it tries to access them.

Now that nodes are initialised with default (empty) variables this means that any unused layout variables (which are initialised as `null`) will cause the exporter to fail.

Exporter should check this value and exclude it if not set.

**Comment by rebeccamadsen** [comment]
This is resolved [here ](https://github.com/codaco/Network-Canvas/pull/856/files#diff-9c5e71fb8a16866df4d2d5d7a477f2d4R197)with ego updates.

Any `null` value needs to be excluded from export because gephi thinks "null" is a string, and has issues with variables that ought to be numbers showing up as strings.
