### ISSUE TITLE
categorical variables with number values become strings

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#878]
For categorical variables, if a `value` for `options` is a number, the display in a node form for toggle buttons (`ToggleButtonGroup`) does not display the value as selected. In redux, the value for that variable is an array with a string version of the number. Possibly the form submit is converting the number value to a string at some point, so the submitted value does not match the option value (good old "1" does not equal 1). If numbers are valid values, they should be handled as numbers.

**Comment by wwqrd** [comment]
Categorical and ordinal variables only have the type 'categorical' or 'ordinal', the intrinsic values are untyped. In architect, they are text inputs, and saved as strings; at the moment it's only possible to make numerical option values in a custom protocol.

If we want to use numerical types either we should expand the top-level types, or we're going to need to assume that anything that can be interpreted as a number is saved that way.

**Comment by rebeccamadsen** [comment]
I originally saw this issue from a protocol created in Architect, and imported to NC, though things may have changed since then. Any ordinal or categorical option value was written out as a number, with no quotes, and then NC received it as a number with no quotes. I didn't see an NC issue with ordinal values, because it was comparing numbers to numbers, but categorical variable options were sometimes comparing a quoted number to a number. 

I think if values were always strings that would work. But I also think if NC handled the option values consistently that would work. Do ordinal variables need numerical value to be ["an ordered scale of values"](https://github.com/codaco/Network-Canvas/wiki/Variable-Types#ordinal)?

**Comment by jthrilly** [comment]
> Categorical and ordinal variables only have the type 'categorical' or 'ordinal', the intrinsic values are untyped. In architect, they are text inputs, and saved as strings; at the moment it's only possible to make numerical option values in a custom protocol.

Sadly, this is not the case: I just tried creating some options for a categorical variable in the latest Architect, and you can indeed create number type option values.

> I think if values were always strings that would work. But I also think if NC handled the option values consistently that would work. Do ordinal variables need numerical value to be ["an ordered scale of values"](https://github.com/codaco/Network-Canvas/wiki/Variable-Types#ordinal)?

In a technical sense, yes. However, the way that we interpret ordinal is that the option values have a meaningful order - this is achieved by giving the researcher the ability to reorder the items. This means they need not be numbers, and that numbers may actually appear out of sequence.

This is not relevant though - what matters is that numerical values definitely should not break in architect!

To solve this:

- When setting these values by clicking a toggle button, we need to check if the value should be stored as a number, and make sure a number is being emitted by `event.target.value`, since this is what redux forms is using (see: https://github.com/erikras/redux-form/issues/3040). 
- Once we have done that, everything should work. If not. we have `isNaN` and `parse={Number}` to help.

**Comment by wwqrd** [comment]
> Sadly, this is not the case: I just tried creating some options for a categorical variable in the latest Architect, and you can indeed create number type option values.

Interesting! This is definitely not what I anticipated, since Architect only uses text inputs for those. Looks like it parses for Number like values. Is this a mistake do we think?

> Categorical and ordinal variables only have the type 'categorical' or 'ordinal', the intrinsic values are untyped.

Do either of you have any thoughts on this? Are we saying that they should always be text, or that they can be a mix of scalars? 

> When setting these values by clicking a toggle button, we need to check if the value should be stored as a number, and make sure a number is being emitted by event.target.value, since this is what redux forms is using (see: erikras/redux-form#3040).

Sounds like you want to mix values, and handle this in UI?

**Comment by jthrilly** [comment]
> Sounds like you want to mix values, and handle this in UI?

Yes, I think the root cause of this "issue" is that the toggle button component isn't correctly setting its value.

We need something like this (from the Number component):

`props.input.onBlur(toInt(e.target.value)),`

but only for instances where the original value was a number. Should be straightforward.
