### ISSUE TITLE
droppable status in side panel

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#883]
"Already mentioned" vs "People from your previous visit" panels are inconsistently triggering when dragging nodes from the main panel to a side panel. It varies from one prompt to the next, and when you restart a session. Sometimes you can delete a node via "people from your previous visit", and sometimes not. Sometimes it errors out. 

For example, drag "Baz" to the main panel. It is droppable on both side panels, even though it isn't present anywhere else in the session. Drop it in "Already mentioned", and `promptIDs` is empty now, though the node is still in the network.

Another example, drag "Baz" to the main panel. Return to the start screen. Navigate to your session again. "Baz" is no longer droppable on "People from your previous visit" even though it should be.

It used to be that in both cases, "Baz" would be droppable on "People from your previous visit" but not on "Already mentioned". I think it should just not be droppable on "Already mentioned" if that's the only prompt in the list.

**Comment by jthrilly** [comment]
> For example, drag "Baz" to the main panel. It is droppable on both side panels, even though it isn't present anywhere else in the session. Drop it in "Already mentioned", and `promptIDs` is empty now, though the node is still in the network.

I think this part is intended behavior - although the crash was due to an error in exporting the actions.

The idea being that you can remove a node from a prompt independently of removing it from the interview, even if it is the last prompt it is on.

**Comment by jthrilly** [comment]
> Another example, drag "Baz" to the main panel. Return to the start screen. Navigate to your session again. "Baz" is no longer droppable on "People from your previous visit" even though it should be.

This was a bad one. It took me 4 hours, and the solution ended up being one line!

The problem was that the `<NodePanel />` component was triggering an incorrect map of node IDs when the `withExternalData` HOC updated the `externalData` prop, because the update was being triggered inside of `componentWillRecieveProps`, and therefore happening before the externalData was available to create the map. Phew.

To say that again simply: `componentWillRecieveProps` was passing a function `nextProps`, and further down the stack was a reference to `this.props` that was undefined. When the missing prop became defined later in the lifecycle, the update function was not called again because the comparison test (which depended on other props) was not passed.

Initial solution was to pass `nextProps.externalData` down the stack to the function that ultimately used it to calculate the node id map. I then realized I could just do the update later in the lifecycle, inside `componentDidUpdate`, and then not have to pass any props anywhere, since they would be available to all functions.
