### ISSUE TITLE
Data export does not include variables not in the codebook, such as those in external data files.

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#940]
Update the export parse to make a best guess about how to encode variables not in the codebook.

**Comment by rebeccamadsen** [comment]
Is this for export to Server, not graphml?

**Comment by jthrilly** [comment]
No this issue was for Server's export. It was actually more of a question than an issue. 

To give a scenario, what happens if I have a JSON external network file that contains an array value for one of the node variables. 

```
{
  thingy: ['one', 'two']
}
```

When this node gets brought into the interview, the variable ID isn't found in the codebook either by ID or name, and so it is left alone. The value isn't touched. So what happens when the network with this node in is being exported by Server?

**Comment by rebeccamadsen** [comment]
I double checked. If a JSON external file has variables that are unused in NC, and thus not in the codebook, the data is still exported to Server for any node that was added to the network. External data nodes (and their variables) that were not pulled into the interview by the user won't be exported because they weren't part of the network, of course.

The value is just treated as a string, so exported as `['one', 'two']`. What would we want to have happen?

**Comment by jthrilly** [comment]
> I double checked. If a JSON external file has variables that are unused in NC, and thus not in the codebook, the data is still exported to Server for any node that was added to the network.

I might have confused you above - I am talking about what happens when this data is then exported _from_ server (as CSV or JSON). 

> The value is just treated as a string, so exported as `['one', 'two']`. What would we want to have happen?

Well, multiple membership categorical variables that ARE in the codebook have that special case applied to them, where the categorical variable is split out into `varaibleName_variableValue` format Boolean variables. I suppose for consistency we might want to have the exporter treat array values without a variable definition in the codebook the same way? What do you think? Otherwise, we end up with some stringified values that the user has to parse out during analysis.

Another issue this brings up is: what about a CSV file that specifies the value of a categorical variable that IS in the codebook, but as a single string value rather than (obviously) an array. Does that get exported correctly?

**Comment by rebeccamadsen** [comment]
I followed the data export through to the CSV and graphml that Server exports, actually. It remains a string `['one', 'two']` value. If we want this to be treated specially, then we could look for quoted arrays to treat them differently, though that makes `[` and `]` special characters we should restrict otherwise?

We also would not have the full list of options for the variable, since the variable isn't defined in the codebook. We could maybe look for an array, and reconstruct options based on what values exist in the exported data, though it would vary depending on which nodes get used in an interview if we did that Server side. We could add it to codebook? Perhaps somewhere in Architect we could have the user verify our "guessed" variable types and options?

Interestingly, I tested a categorical variable that IS in codebook, and Server actually exports it correctly (through the magic of lodash's `includes`), but the overview chart doesn't show it correctly (because it's a quoted string value instead of an array). This was true for both an array and a single string value.

**Comment by jthrilly** [comment]
> I followed the data export through to the CSV and graphml that Server exports, actually. It remains a string `['one', 'two']` value. If we want this to be treated specially, then we could look for quoted arrays to treat them differently, though that makes `[` and `]` special characters we should restrict otherwise?

Okay, so in the case of external data in JSON network format (for argument's sake), why would these values be strings rather than arrays? At what point are they being converted to strings? If it is within Server (during the export) then yes, we just need to build in our exception.

> We also would not have the full list of options for the variable, since the variable isn't defined in the codebook. We could maybe look for an array, and reconstruct options based on what values exist in the exported data, though it would vary depending on which nodes get used in an interview if we did that Server side.

The options for the variable defined in the codebook are only really needed when rendering an input component to allow the user to select a value. So yes, in the case of external data, we would have to iterate the nodelist, and compile a map of possible values based on the nodes in the interview network.  Not ideal in the sense that it is based only on interview nodes, but no data is lost and the format is consistent, which is the main thing.

**Comment by jthrilly** [comment]
Final implementation is that these values are simple encoded as strings, and the researcher must decide what to do with them.

https://github.com/codaco/network-exporters/pull/4
